version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Print Directory 
          command: pwd
      - run:
          name: Show contents
          command: ls 

